<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\MaterialDesignIcons\.github\ISSUE_TEMPLATE.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerValidationModule.Client\CustomerValidationModule.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.30" />
  </ItemGroup>

</Project>
